package main

func main() {
	// values()
	// variables()
	// constants()
	// forloop()
	// ifelse()
	// switchcase()
	// arraystest()
	// slicestest()
	// mapstest()
	// rangetest()
	// functest()
	// variadicFunction()
	// clousres()
	// pointerstest()
	// stringsrunestest()
	// structstest()
	// methodstest()
	// interfacestest()
	// structembeddingtest()
	// genericstest()
	// errorstest()
	// goroutinestest()
	// waitgroupstest()
	// channelstest()
	// channelBufferingTest()
	// channelsynctest()
	// channelsDirectionTest()
	// selectChannelTest()
	channelsTimeOutTest()

}
